server {
    listen 8081;
    server_name localhost;

    root ./www/site1;
    index index.html;

    location /new/ {
        allow_methods GET;
    }
    location /old{
        return 301 /new/;
    }
}