server {
    listen 8080;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8081;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8082;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8083;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8084;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8085;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8086;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8087;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8088;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8089;
    server_name localhost;
    root ./www/site1;
    index index.html;
}
server {
    listen 8090;
    server_name localhost;
    root ./www/site1;
    index index.html;
}